Add explicit link to run_all_examples.py
PyFstat/PyFstat pull request #291
Opened 2021-03-15 14:46 UTC by Rodrigo-Tenorio

Solve #287

2021-03-15 18:53 UTC, dbkeitel requested changes
Actually, if the user hasn't cloned the repository, just downloading that one file won't get them far...  

I don't think github provides download links per directory without weird external tools, so I think we have to recommend the three options

- git clone
- download full tree from Zenodo
- download full tree from github

Ideally, versioned docs should point to the matching Zenodo version and "latest" docs to github... but I suspect the effort would be disproportionate.

2021-03-16 22:08 UTC, dbkeitel approved these changes

2021-03-16 22:09 UTC, dbkeitel commented
@khanx169 is this close enough to what you had in mind? Output page is here: https://pyfstat--291.org.readthedocs.build/en/291/examples.html

2021-03-17 17:36 UTC, khanx169 commented
> @khanx169 is this close enough to what you had in mind? Output page is here: https://pyfstat--291.org.readthedocs.build/en/291/examples.html

Yes, that looks good. Thanks!

2021-03-17 17:54 UTC, merged