Change color and title
PyFstat/PyFstat pull request #308
Opened 2021-04-07 14:43 UTC by Rodrigo-Tenorio

I attempted to improve titles by using `g` format, but it's tricky
![PyFstat_example_semi_coherent_binary_search_using_MCMC_corner](https://user-images.githubusercontent.com/49152330/113885796-6c372380-97c0-11eb-96de-0e235a9348fe.png)

2021-04-07 16:21 UTC, dbkeitel commented
- [ ] In the example, `tp` is a bit confusing because it uses exponential notation for the median and normal notation for the error bars. No, wait actually, the problem is in using exponential notation for _**GPS time variables**_ in general. We need a special logic for those.

- [ ] Also, for the quantities _with_ units, the `[s] = ...` notation is weird but intuitively clear, but for the `asini` without units the `[] = ...` makes no sense at all. While you're at it, could you move the units bracket to the first line right behind the variable name, ideally also suppressing it if empty?

2021-04-08 15:38 UTC, Rodrigo-Tenorio commented
Quite more work is needed to tweak around with the numerical values. 
Let's leave this as is, colors and labels are better.

![PyFstat_example_semi_coherent_binary_search_using_MCMC_corner](https://user-images.githubusercontent.com/49152330/114055471-18483f80-9891-11eb-8971-eaded15f1d01.png)

2021-04-09 09:45 UTC, dbkeitel requested changes
We're back to the error bars potentially being shown as "0.00" then, which is bad. But having a bit of a look at `corner.py` internals, I think there's really nothing we can do about it on our end. We should consider sending them a PR implementing either
1. allowing `title_fmt` to be a dictionary over parameters
2. a "smart" mode that first applies `title_fmt` to the error bars, then formats the median to match significant figures

Before merging this one though, could you just add parameterst to `plot_corner()` to change both the main and the truths color please? I like the new slateblue-orange scheme as a default, but being able to make it all-black for printing would be nice too.

2021-04-09 09:51 UTC, dbkeitel commented
Someone's been thinking about similar lines for the quantiles header already, but no results yet: https://github.com/dfm/corner.py/issues/108

2021-04-09 10:02 UTC, dbkeitel commented
Actuallt, we **can** do it on our end: pass `title_fmt=None` to `corner.corner` and then add the titles ourselves after, reusing the code from https://github.com/dfm/corner.py/blob/main/src/corner/core.py#L212 . The "smart" way is a bit tricky to get right, so I'd just go with a dict of "good standard" formats for our known set of parameters (i.e. ".2g" for most, something custom for Tgps, anything else...?). This will mean repeating quantile computations, but to quote the corner.py code comment: "This might redo unneeded computation but who cares."

Do you want to give it a try inside this PR @Rodrigo-Tenorio or should we merge first and do it separately?

2021-04-09 14:08 UTC, Rodrigo-Tenorio commented
Ok, I agree with this:
- [ ] Add density color and truths color as an argument at PyFstat's level

I'll do it now and we can merge this PR.

See #311 for discussion about the title.

2021-04-09 14:21 UTC, Rodrigo-Tenorio commented
Both arguments can be already accessed through `kwargs`. I'd prefer not to extend that plate of conditional spaghetti.

Color scheme is set to black-gray.

@dbkeitel PR is go.

2021-04-09 15:42 UTC, dbkeitel approved these changes
Ok, one kwarg to rule them all!

2021-04-09 15:42 UTC, merged