Add tutorial notebooks
PyFstat/PyFstat pull request #395
Opened 2022-05-03 14:09 UTC by Rodrigo-Tenorio

Long time awaited PR: Tutorials on how to use PyFstat to do different things!

For now:

- [ ] How to generate Gaussian noise.
- [ ] How to inject signals.

To do:
- [ ] Make sure binder works.

2022-05-04 16:20 UTC, Rodrigo-Tenorio commented
@mj-will tutorial 0 is go for comments :rocket:

2022-05-10 12:27 UTC, mj-will commented
So generally I think it looks really good but I do have a couple of comments

*  The section links in both notebooks don't seem to work for me, not sure why (it could be VSCode) but probably worth double-checking they work
*  There are some unused imports in the signal notebook
* Might be worth starting explicitly that these notebooks need at least v1.* (which ever the latest version is) just in case conda/pip installs an older version

2022-05-10 13:51 UTC, Rodrigo-Tenorio commented
@dbkeitel I'm having problems with binder, any problems in merging and then submitting PR to fix it if it fails in master?

2022-05-11 15:52 UTC, dbkeitel requested changes

2022-05-11 15:52 UTC, dbkeitel commented on examples/tutorials/0_generating_noise.ipynb
> +    "and the advanced Virgo detector `V1`."
Add comment on expected formats for `sqrtSX` and `timestamps` for multi-IFO?

2022-05-11 15:52 UTC, dbkeitel commented on examples/tutorials/0_generating_noise.ipynb
> +    "                \"outdir\": \"Pyfstat_example_data\",\n",
and in all further example calls below, and also the signal notebook

2022-05-11 15:52 UTC, dbkeitel commented on examples/tutorials/0_generating_noise.ipynb
> +    "                \"Band\": 1.,               # Frequency band-width [Hz]\n",
and in all further example calls below

2022-05-11 15:52 UTC, dbkeitel commented on examples/tutorials/1_generating_signals.ipynb
> +    "of $20\\;\\text{Hz}^{-1/2}$."
This sounds too optimistic for visual features according to my intuition, but I have problems running locally right now, will think about / test it again later.

2022-05-11 17:14 UTC, dbkeitel commented on examples/tutorials/1_generating_signals.ipynb
> +    "signal_parameters = pyfstat.AllSkyInjectionParametersGenerator(\n",
Can you rename this variable `signal_parameters_generator` or something, to make it easier to run cells in different order, and make it more explicit that this is something different than the simple dict before.

2022-05-12 09:52 UTC, dbkeitel approved these changes

2022-05-12 09:53 UTC, merged